version: '3.0'
services:
  samba:
    build: .
    image: aprabh/alpine-samba:v1
    container_name: samba
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    restart: unless-stopped
    volumes:
      # share the required dir from Host -> Container
      - /media/pi/samba:/home
